[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "prague"
solc_version = "0.8.28"
via_ir = true

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
